
#line 3 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int FlexScanner::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 122
#define YY_END_OF_BUFFER 123
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[322] =
    {   0,
        0,    0,    0,    0,    0,    0,  123,  121,  114,  115,
      113,  113,  121,  113,  113,  113,  113,  113,  113,  113,
      113,  113,    1,    1,    1,    1,  113,  113,  113,  113,
      113,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,  113,
        4,  121,  122,  118,  120,  119,   53,    0,  107,    0,
        0,  108,    0,   68,   54,   71,   66,   64,    0,   65,
        0,    0,    0,    0,    0,  116,    0,   67,    0,    1,
        1,    1,    2,    3,    0,    0,    0,  105,  104,    0,
       73,  106,    0,   62,   51,   52,   50,   63,    5,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   33,    0,    0,    0,    0,    0,    0,    0,
       38,    0,    0,    0,   94,    0,    0,    0,    0,   47,
       56,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   26,    0,    0,   72,    0,   55,  118,
      117,   14,    0,  112,   58,   61,   60,    0,   35,    0,
      109,    1,   15,   13,    0,  111,   49,   69,   70,   84,
        0,   29,   57,    0,    0,    0,    0,    0,    0,    0,
        0,   90,   24,    9,    0,    0,    0,    0,   92,    0,
        0,    0,    0,    0,   23,   25,   79,    0,    0,   46,

       28,   31,   47,  102,   81,    0,    0,    0,    0,    7,
        0,    0,   95,    0,    0,    0,    0,   30,    0,    0,
       97,    0,   45,    0,   59,   35,   16,   86,    0,   87,
       88,    0,   18,   89,    0,    0,   91,    0,   39,    0,
       37,    0,   11,    0,    0,    0,    0,    0,   27,    0,
        0,   17,  101,   21,   44,   41,   96,   12,    8,   85,
        0,    0,    0,   98,    0,    0,  110,    6,   40,   10,
        0,    0,   82,    0,   93,    0,   78,   76,   74,   80,
        0,   20,   22,   42,    0,    0,    0,   32,    0,    0,
        0,    0,    0,    0,    0,   19,    0,    0,   36,   48,

       83,    0,   34,    0,    0,   43,    0,    0,    0,    0,
        0,    0,    0,   99,    0,    0,  103,  100,   77,   75,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   15,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   56,   57,   58,   59,    1,   29,   30,   31,   32,

       60,   34,   61,   36,   37,   38,   39,   62,   63,   64,
       43,   44,   65,   66,   47,   67,   49,   50,   51,   52,
       53,   54,   15,   68,   15,   15,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    2,    3,    1,    2,    2,    1,    1,    1,    2,
        4,    4,    5,    4,    1,    4,    1,    4,    6,    6,
        6,    6,    2,    1,    4,    1,    1,    4,    6,    6,
        6,    6,    6,    6,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    1,    4,    1,    4,    4,    6,
        7,    7,    7,    7,    7,    7,    7,    4
    } ;

static yyconst flex_int16_t yy_base[336] =
    {   0,
        0,    0,    0,    0,   66,   67,  564,  565,  565,  565,
      538,   66,  559,    0,  536,   63,  565,  535,  534,   57,
      541,   65,   72,   84,   90,   78,  114,   60,  532,   49,
        0,   99,   50,  115,   99,  109,  127,  565,  134,  120,
      145,  513,   62,  144,  121,  159,   91,  519,  511,  528,
      168,  195,  565,    0,  565,  534,  565,   82,  565,  548,
      547,  565,  542,  565,  565,  565,  565,  565,  545,  565,
      482,  479,  478,  484,  526,  565,  539,  565,  201,  210,
      216,  222,  565,  565,    0,  226,  160,  186,  193,  538,
      565,  224,  514,  514,  565,  565,  565,  513,    0,  490,

      493,  503,  502,   77,  496,  503,   53,   95,  494,  139,
      208,  217,  565,  153,  112,  214,  499,  212,  486,  188,
      565,  479,  496,  213,  565,  213,  220,  232,  225,  219,
      565,  224,  240,  228,  229,  497,  243,  235,  242,  496,
      259,  477,  249,  565,  486,  246,  565,  267,  279,    0,
      565,  515,  518,  565,  565,  565,  565,  455,  287,  516,
      565,  296,    0,  565,  515,  565,  565,  565,  565,  565,
      470,  565,  565,  487,  260,  261,  486,  265,  266,  485,
      466,  476,  565,  565,  461,  277,  265,  271,  565,  272,
      281,  467,  290,  480,  565,  565,  565,  465,  464,  565,

      293,  565,  565,  565,  565,  459,  287,  474,  468,  456,
      470,  469,  464,  299,  285,  287,  468,  565,  469,  288,
      461,  294,  565,  493,  565,  331,  565,  565,  442,  565,
      565,  455,  565,  565,  294,  294,  565,  464,  565,  308,
      565,  449,  565,  298,  462,  305,  300,  316,  565,  459,
      309,  565,  565,  307,  565,  413,  565,  565,  565,  565,
      416,  317,  336,  565,  337,  447,  565,  565,  565,  565,
      432,  416,  565,  326,  565,  413,  565,  405,  399,  565,
      367,  331,  565,  565,  347,  350,  336,  565,    0,  348,
      353,  353,  156,  339,  351,  565,  350,  332,  565,    0,

      565,  357,  565,  336,  331,  565,  219,  169,  339,  174,
      107,  342,   52,  565,  341,  343,  565,  565,  565,  565,
      565,  405,  412,  419,  426,  433,  439,  445,  452,  459,
      466,   71,  473,  480,  482
    } ;

static yyconst flex_int16_t yy_def[336] =
    {   0,
      321,    1,  322,  322,  323,  323,  321,  321,  321,  321,
      321,  324,  325,  326,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  327,  321,  321,  321,
      328,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  329,  321,  321,  321,  324,  321,  324,
      325,  321,  326,  321,  321,  321,  321,  321,  330,  321,
      321,  321,  321,  321,  321,  321,  331,  321,  321,  321,
      321,  321,  321,  321,  332,  321,  327,  327,  327,  333,
      321,  327,  321,  321,  321,  321,  321,  321,  328,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  329,
      321,  326,  330,  321,  321,  321,  321,  321,  321,  331,
      321,  321,  332,  321,  333,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  334,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  334,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  335,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  335,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
        0,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321
    } ;

static yyconst flex_int16_t yy_nxt[634] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,    8,
       17,   17,   18,   19,   17,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   17,   31,   32,   33,
       34,   35,   36,   37,   38,   38,   39,   38,   38,   40,
       41,   42,   43,   44,   38,   45,   46,   47,   38,   38,
       48,   49,   38,   38,   17,    8,   17,   50,    8,   36,
       38,   40,   41,   42,   38,   51,   47,   52,   55,   55,
       59,   65,   69,   97,   98,   93,  163,   76,   56,   56,
      318,   70,   77,   94,   95,  177,   59,   66,   79,   78,
       80,   80,   81,   82,   79,  107,   82,   82,   82,   82,

       79,   83,   80,   80,   81,   82,   79,  131,   81,   81,
       81,   82,  177,   83,   84,  107,   71,   72,   73,  143,
       74,   60,  174,   85,   88,   89,   84,  131,  100,  101,
      102,  112,   84,  144,  178,  316,   90,   60,   91,   86,
      103,  113,  174,  108,  104,  105,  106,  109,  114,  135,
      115,   86,  124,  136,  110,  117,  178,  111,  112,  187,
      116,  125,  103,  118,  104,  106,  119,  121,  122,  120,
      114,  180,  115,  126,  109,  123,  110,  127,  187,  124,
      136,   92,  164,  125,  321,  185,  132,  128,  119,  133,
      304,  124,  134,  129,  122,  137,  135,  123,  180,  186,

      136,  138,  315,  139,  127,  313,  140,  141,  164,  133,
      321,  142,  185,   86,   86,  164,  304,  321,  124,  162,
      162,  162,  162,  139,   83,  140,   79,  148,   80,   80,
       81,   82,   79,  193,   81,   81,   81,   82,   79,   83,
       82,   82,   82,   82,   86,   86,  164,  183,  321,  181,
      188,  191,   84,  193,  182,   83,  184,  189,   84,  197,
      196,  199,  149,  200,  202,  198,  203,  204,  206,  205,
      211,  181,  312,  191,  209,  210,  207,   86,  184,  196,
      215,  201,  208,  199,  213,  203,  202,  216,  218,  205,
      221,  223,  211,   86,  210,  212,  214,   86,   86,  219,

      215,  230,  231,  226,  233,  234,  213,  216,   83,  239,
      240,  223,  221,  227,  162,  162,  162,  162,  241,  242,
      243,  219,  245,  230,  231,  249,  233,  234,  251,  224,
      240,  258,  259,  265,  260,  263,  239,  241,  242,  270,
      273,  271,  243,  275,  277,  278,   86,  226,  283,  245,
      251,  259,  249,  260,  263,  265,  282,  227,  258,  270,
      271,  279,  280,  275,  286,  278,  277,  273,  287,  288,
      283,  291,  296,  305,  317,  282,  299,  308,  314,  311,
      319,  279,  320,  286,  310,  309,  307,  306,  303,  302,
      301,  291,  298,  297,  296,  287,  288,  308,  299,  305,

      314,  317,  319,  295,  320,   53,   53,   53,   53,   53,
       53,   53,   54,   54,   54,   54,   54,   54,   54,   58,
       58,   58,   58,   58,   58,   58,   61,   61,   61,   61,
       61,   61,   61,   63,   63,  294,   63,   63,   63,   63,
       87,  293,   87,  292,   87,   87,   99,  290,  289,  267,
       99,   99,  150,  150,  285,  150,  284,  150,  150,  153,
      153,  153,  153,  153,  153,  153,  160,  160,  160,  160,
      160,  160,  160,  165,  165,  165,  165,  165,  165,  165,
      266,  266,  266,  266,  266,  266,  266,  300,  300,  281,
      276,  274,  272,  269,  268,  267,  264,  262,  261,  257,

      256,  255,  254,  253,  252,  250,  248,  247,  246,  244,
      238,  237,  236,  235,  232,  229,  228,  166,  161,  225,
      154,  152,  222,  220,  217,  212,  195,  194,  192,  190,
      179,  176,  175,  173,  172,  171,  170,  169,  168,  167,
      166,  161,  159,  158,  157,  156,  155,  154,  152,   62,
      321,  151,  147,  146,  145,  130,   96,   75,   68,   67,
       64,   62,   57,  321,    7,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321
    } ;

static yyconst flex_int16_t yy_chk[634] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    6,
       12,   16,   20,   30,   30,   28,  332,   22,    5,    6,
      313,   20,   22,   28,   28,  107,   58,   16,   23,   22,
       23,   23,   23,   23,   26,   33,   26,   26,   26,   26,

       24,   23,   24,   24,   24,   24,   25,   43,   25,   25,
       25,   25,  107,   24,   23,   33,   20,   20,   20,   47,
       20,   12,  104,   23,   27,   27,   24,   43,   32,   32,
       32,   35,   25,   47,  108,  311,   27,   58,   27,   23,
       32,   35,  104,   34,   32,   32,   32,   34,   36,   45,
       36,   24,   40,   45,   34,   37,  108,   34,   35,  115,
       36,   40,   32,   37,   32,   32,   37,   39,   39,   37,
       36,  110,   36,   41,   34,   39,   34,   41,  115,   40,
       45,   27,   87,   40,   87,  114,   44,   41,   37,   44,
      293,   46,   44,   41,   39,   46,   51,   39,  110,  114,

       51,   46,  310,   46,   41,  308,   46,   46,   88,   44,
       88,   46,  114,   52,   52,   89,  293,   89,   46,   79,
       79,   79,   79,   46,   52,   46,   80,   51,   80,   80,
       80,   80,   81,  120,   81,   81,   81,   81,   82,   80,
       82,   82,   82,   82,   86,   86,   92,  112,   92,  111,
      116,  118,   80,  120,  111,   86,  112,  116,   81,  126,
      124,  127,   52,  128,  129,  126,  130,  132,  133,  132,
      135,  111,  307,  118,  134,  134,  133,   80,  112,  124,
      138,  128,  133,  127,  137,  130,  129,  139,  141,  132,
      143,  146,  135,   86,  134,  148,  137,  149,  149,  141,

      138,  175,  176,  159,  178,  179,  137,  139,  149,  186,
      187,  146,  143,  159,  162,  162,  162,  162,  188,  190,
      191,  141,  193,  175,  176,  201,  178,  179,  207,  148,
      187,  214,  215,  222,  216,  220,  186,  188,  190,  235,
      240,  236,  191,  244,  246,  247,  149,  226,  254,  193,
      207,  215,  201,  216,  220,  222,  251,  226,  214,  235,
      236,  248,  248,  244,  262,  247,  246,  240,  263,  265,
      254,  274,  282,  294,  312,  251,  287,  298,  309,  305,
      315,  248,  316,  262,  304,  302,  297,  295,  292,  291,
      290,  274,  286,  285,  282,  263,  265,  298,  287,  294,

      309,  312,  315,  281,  316,  322,  322,  322,  322,  322,
      322,  322,  323,  323,  323,  323,  323,  323,  323,  324,
      324,  324,  324,  324,  324,  324,  325,  325,  325,  325,
      325,  325,  325,  326,  326,  279,  326,  326,  326,  326,
      327,  278,  327,  276,  327,  327,  328,  272,  271,  266,
      328,  328,  329,  329,  261,  329,  256,  329,  329,  330,
      330,  330,  330,  330,  330,  330,  331,  331,  331,  331,
      331,  331,  331,  333,  333,  333,  333,  333,  333,  333,
      334,  334,  334,  334,  334,  334,  334,  335,  335,  250,
      245,  242,  238,  232,  229,  224,  221,  219,  217,  213,

      212,  211,  210,  209,  208,  206,  199,  198,  194,  192,
      185,  182,  181,  180,  177,  174,  171,  165,  160,  158,
      153,  152,  145,  142,  140,  136,  123,  122,  119,  117,
      109,  106,  105,  103,  102,  101,  100,   98,   94,   93,
       90,   77,   75,   74,   73,   72,   71,   69,   63,   61,
       60,   56,   50,   49,   48,   42,   29,   21,   19,   18,
       15,   13,   11,    7,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,

      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[123] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 
    1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "yare.l"
#line 2 "yare.l"
	#include "yare.tab.h"
	#include "YareScanner.h"
	#include "constantes.h"
	// XXX  #include "astnode.h"
	#include <cstring>
	#include <cctype>
	#include <cstdlib>
	#include <iostream>
	#include <cstdio>
	#include <cstring>
	#include <bitset>
	#include <limits>

	void append_char(char *s, char c) {
    	unsigned int length = strlen(s);
    	s[length] = c;
    	s[length + 1] = '\0';
	}

	void remove_first_char(char *s) {
    	memmove(s, s + 1, strlen(s));
	}

	void remove_last_char(char *s) {
    	s[strlen(s) - 1] = '\0';
	}

	// Opvar:
	extern char opVar[4];
	using std::endl;
	using std::cout;
	using std::cerr;


#line 733 "lex.yy.cc"

#define INITIAL 0
#define STRING 1
#define IN_COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 42 "yare.l"


#line 843 "lex.yy.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = & std::cin;

		if ( ! yyout )
			yyout = & std::cout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 322 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 565 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "yare.l"
{
	lexema->valnum = strtold(yytext, NULL);
	return YL::YareParser::token::NUMERIC;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "yare.l"
{
	
	yytext[strlen(yytext) - 1] = '\0';
	std::string _str(yytext);
	unsigned long long _binary = std::bitset<std::numeric_limits<unsigned long long>::digits>(_str).to_ulong();
	lexema->valnum = _binary;

	return YL::YareParser::token::NUMERIC;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "yare.l"
{
	yytext[strlen(yytext) - 1] = '\0';
	char *end;
	unsigned long _octal = strtoul(yytext, &end, 8);
	lexema->valnum = _octal;
	return YL::YareParser::token::NUMERIC;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 67 "yare.l"
{
						// TODO Revisar esto con calma
	if(isupper(*yytext))
		lexema->sIndex = tolower(*yytext) - 'a';
	else
		lexema->sIndex = *yytext - 'a';
	return YL::YareParser::token::VARIABLE;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 76 "yare.l"
{
	strcpy(lexema->identificador, yytext);
	for(unsigned _i_ = 0; _i_ < strlen(lexema->identificador); _i_++)
		if(isalpha(lexema->identificador[_i_]) && isupper(lexema->identificador[_i_]))
			lexema->identificador[_i_] = tolower(lexema->identificador[_i_]);
	return YL::YareParser::token::ARRAY_ID;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 84 "yare.l"
{
	return YL::YareParser::token::ARRAY_C;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 88 "yare.l"
{
	return YL::YareParser::token::ARRAY_PUT;	
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "yare.l"
{
	return YL::YareParser::token::ARRAY_SORT;	
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 96 "yare.l"
{
	return YL::YareParser::token::ARRAY_DEL;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 100 "yare.l"
{
	return YL::YareParser::token::ARRAY_CLEAR;	
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 104 "yare.l"
{
	return YL::YareParser::token::ARRAY_FILL;	
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 108 "yare.l"
{
	return YL::YareParser::token::ARRAY_SIZE;		
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "yare.l"
{
	strcpy(lexema->identificador, yytext);
	for(unsigned _i_ = 0; _i_ < strlen(lexema->identificador); _i_++)
		if(isalpha(lexema->identificador[_i_]) && isupper(lexema->identificador[_i_]))
			lexema->identificador[_i_] = tolower(lexema->identificador[_i_]);
	return YL::YareParser::token::ID;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 120 "yare.l"
{
	strcpy(lexema->nameFunction, yytext);
	lexema->nameFunction[strlen(lexema->nameFunction)] = '\0';
	return YL::YareParser::token::FUNCNAME;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 126 "yare.l"
{
	lexema->valnum = strtold(yytext, NULL);
	return YL::YareParser::token::NUMERIC;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 131 "yare.l"
{
	// 676 ...? 8729834, expr ...? expr
	return YL::YareParser::token::RANGE_RANDOM;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 136 "yare.l"
{
	return YL::YareParser::token::PROC;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 140 "yare.l"
{
	return YL::YareParser::token::CALL;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 144 "yare.l"
{
	return YL::YareParser::token::PRINTN;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 148 "yare.l"
{
	return YL::YareParser::token::PRINT;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 152 "yare.l"
{
	return YL::YareParser::token::PUTS;	
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 156 "yare.l"
{
	return YL::YareParser::token::PUTSN;	
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 160 "yare.l"
{
	return YL::YareParser::token::INC;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 164 "yare.l"
{
	return YL::YareParser::token::DEC;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 168 "yare.l"
{
	return YL::YareParser::token::LETSET_ASSIGN;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 172 "yare.l"
{
	return YL::YareParser::token::TO;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 176 "yare.l"
{
	return YL::YareParser::token::MOVE;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 180 "yare.l"
{
	// mov x, 1 + 2;
	return YL::YareParser::token::MOV_ASM;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 185 "yare.l"
{
	// dd x, 1+ 2 * 3;
	return YL::YareParser::token::ADD_ASM;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 190 "yare.l"
{
	// add x, 1+ 2 * 3;
	return YL::YareParser::token::SUB_ASM;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 195 "yare.l"
{
	// mul x, 2;
	return YL::YareParser::token::MUL_ASM;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 200 "yare.l"
{
	return YL::YareParser::token::WHILE;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 204 "yare.l"
{
	return YL::YareParser::token::DO;	
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 208 "yare.l"
{
	return YL::YareParser::token::FOREACH;		
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 212 "yare.l"
{
	return YL::YareParser::token::ELIPSIS;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 216 "yare.l"
{
	return YL::YareParser::token::SYSTEM;	
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 220 "yare.l"
{
	return YL::YareParser::token::EXIT;		
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 224 "yare.l"
{
	return YL::YareParser::token::IF;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 228 "yare.l"
{
	return YL::YareParser::token::ELSE;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 232 "yare.l"
{
	return YL::YareParser::token::BREAK;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 236 "yare.l"
{
	return YL::YareParser::token::READ;	
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 240 "yare.l"
{
	return YL::YareParser::token::READP;	
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 244 "yare.l"
{
	return YL::YareParser::token::PRASCII;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 248 "yare.l"
{
	return YL::YareParser::token::RAND;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 252 "yare.l"
{
	return YL::YareParser::token::XOROP;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 256 "yare.l"
{
	return YL::YareParser::token::MOD_WORD;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 260 "yare.l"
/* Expressions with WORDS */	{
	return YL::YareParser::token::EXPR_NOT;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 264 "yare.l"
{	
	char *__elemento = strtok(yytext, ".");
	__elemento = strtok(NULL, ".");

	for(unsigned i = 0; i < N_CONST; i++) {
		if(strcmp(__elemento, consts[i].const_str) == 0) {
			lexema->valnum  = consts[i].value;
			return YL::YareParser::token::NUMERIC; 
		}
	}
	cerr << "Error, constante no identificada 'const." << __elemento << "'\n";
	exit(EXIT_FAILURE);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 278 "yare.l"
{
	return YL::YareParser::token::SWAP_OP;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 282 "yare.l"
{
	// Greater or equal:
	return YL::YareParser::token::GE;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 287 "yare.l"
{
	// Less or equal:
	return YL::YareParser::token::LE;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 292 "yare.l"
{
	// Equal:
	return YL::YareParser::token::EQ;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 297 "yare.l"
{
	// Not equal:
	return YL::YareParser::token::NE;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 302 "yare.l"
{
	return YL::YareParser::token::AND;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 306 "yare.l"
{
	return YL::YareParser::token::OR;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 310 "yare.l"
{
	return YL::YareParser::token::OR;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 314 "yare.l"
{
	return YL::YareParser::token::AND;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 318 "yare.l"
{
	// Equal shell operator ==
	return YL::YareParser::token::EQ;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 323 "yare.l"
{
	// Not equal shell operator !=
	return YL::YareParser::token::NE;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 328 "yare.l"
{
	//  Less shell operator <
	return YL::YareParser::token::_LT_;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 333 "yare.l"
{
	//  Great shell operator >
	return YL::YareParser::token::_GT_;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 338 "yare.l"
{
	return YL::YareParser::token::SHIFTLEFT;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 342 "yare.l"
{					
	return YL::YareParser::token::SHIFTRIGHT; 
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 346 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_MAS;
} 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 350 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_MENOS;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 354 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_MUL;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 358 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_DIV;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 362 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_MOD;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 366 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_SHIFTLEFT;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 370 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_SHIFTRIGHT;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 374 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_AND;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 378 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_POW;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 382 "yare.l"
{
	return YL::YareParser::token::PASCAL_ASSIGN;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 386 "yare.l"
{
	// "menor"
	return YL::YareParser::token::EXPR_MENOR;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 391 "yare.l"
{
	// "menorigual"
	return YL::YareParser::token::EXPR_MENORIGUAL;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 396 "yare.l"
{
	// "mayor"
	return YL::YareParser::token::EXPR_MAYOR;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 401 "yare.l"
{
	// "mayorigual"
	return YL::YareParser::token::EXPR_MAYORIGUAL;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 406 "yare.l"
{
	return YL::YareParser::token::EXPR_IGUAL;	
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 410 "yare.l"
{
	return YL::YareParser::token::EXPR_MAS;	
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 414 "yare.l"
{
	return YL::YareParser::token::EXPR_MENOS;		
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 418 "yare.l"
{
	return YL::YareParser::token::EXPR_MUL;			
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 422 "yare.l"
{
	return YL::YareParser::token::EXPR_DIV;			
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 426 "yare.l"
{
	return YL::YareParser::token::EXPR_ELEVADO;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 430 "yare.l"
{
	return YL::YareParser::token::ABS;	
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 434 "yare.l"
{
	return YL::YareParser::token::SQRT;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 438 "yare.l"
{
	return YL::YareParser::token::ACOS;	
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 442 "yare.l"
{
	return YL::YareParser::token::ASIN;	
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 446 "yare.l"
{
	return YL::YareParser::token::ATAN;	
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 450 "yare.l"
{
	return YL::YareParser::token::CEIL;	
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 454 "yare.l"
{
	return YL::YareParser::token::COS;	
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 458 "yare.l"
{
	return YL::YareParser::token::COSH;	
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 462 "yare.l"
{
	return YL::YareParser::token::EXP;		
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 466 "yare.l"
{
	return YL::YareParser::token::FLOOR;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 470 "yare.l"
{
	return YL::YareParser::token::LN;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 474 "yare.l"
{
	return YL::YareParser::token::SIN;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 478 "yare.l"
{
	return YL::YareParser::token::SINH;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 482 "yare.l"
{
	return YL::YareParser::token::TAN;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 486 "yare.l"
{
	   return YL::YareParser::token::TANH;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 490 "yare.l"
{
	return YL::YareParser::token::FACTORIAL;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 494 "yare.l"
{
	return YL::YareParser::token::SUMATORIA;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 498 "yare.l"
{
	return YL::YareParser::token::PUSH;	
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 502 "yare.l"
{
	return YL::YareParser::token::POP;	
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 506 "yare.l"
{
	return YL::YareParser::token::STACK_SIZE;		
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 510 "yare.l"
{
	return YL::YareParser::token::FACE_HAPPY;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 514 "yare.l"
{
	return YL::YareParser::token::FACE_SAD;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 518 "yare.l"
{
	return YL::YareParser::token::FACE_NO;
}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 522 "yare.l"
{
	// std::cout << "String found: '" << yytext << "'" << endl;
	char *string_final = (char *)malloc(strlen(yytext) + 1);
	string_final[0] = '\0';
    unsigned i;

    bool upper = false;
    bool lower = false;

    for(i = 0; yytext[i] != '\0'; i++) {
        if(yytext[i] == '\\') {
            switch(yytext[i + 1]) {
                case 'n':
                    append_char(string_final, '\n');
                    i++;
                    break;
                case 't':
                    append_char(string_final, '\t');
                    i++;
                    break;
                case 's':
                    append_char(string_final, ' ');
                    i++;
                    break;
                case 'b':
                    append_char(string_final, '\b');
                    i++;
                    break;
                case 'r':
                    append_char(string_final, '\r');
                    i++;
                    break;
                case 'f':
                    append_char(string_final, '\f');
                    i++;
                    break;
                case 'q':
                    append_char(string_final, '"');
                    i++;
                case '\\':
                	append_char(string_final, '\\');
                	i++;
                case 'u':
                	upper = true;
                	i++;
                    break;

                case 'l':
                	lower = true;
                	i++;
                    break;

                default:
                    if(isdigit(yytext[i + 1]) == true) {
                        unsigned n_newline = yytext[i + 1] - '0';
                        unsigned _k = 0;
                        for(_k = 0; _k < n_newline; _k++)
                            append_char(string_final, '\n');
                            i++;
                    }
            }
        } else {
            if(upper && isalpha(yytext[i])) {
            	append_char(string_final, toupper(yytext[i]));
            	upper = false;
            } else if (lower && isalpha(yytext[i])){
            	append_char(string_final, tolower(yytext[i]));
            	lower = false;
            } else {
            	append_char(string_final, yytext[i]);
            }
        }
    }
    
    remove_first_char(string_final);
    remove_last_char(string_final);

    strncpy(lexema->cadena, string_final, strlen(string_final) + 1);

	return YL::YareParser::token::CADENA;
}
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 604 "yare.l"
{;}		/* Comentarios tipo shell, perl, python, etc */
	YY_BREAK
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 605 "yare.l"
{;}		/* Comentarios estilo C++ */
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 606 "yare.l"
{;}		/* Comentarios estilo basic */
	YY_BREAK
case 111:
/* rule 111 can match eol */
YY_RULE_SETUP
#line 607 "yare.l"
{;}		/* Comentarios estilo batch */
	YY_BREAK
case 112:
/* rule 112 can match eol */
YY_RULE_SETUP
#line 608 "yare.l"
{;}		/* Comentarios estilo SQL */
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 610 "yare.l"
{
	return *yytext;
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 614 "yare.l"
{;}
	YY_BREAK
case 115:
/* rule 115 can match eol */
YY_RULE_SETUP
#line 615 "yare.l"
{ ; }
	YY_BREAK

case 116:
YY_RULE_SETUP
#line 618 "yare.l"
BEGIN(IN_COMMENT);
	YY_BREAK


case 117:
YY_RULE_SETUP
#line 621 "yare.l"
BEGIN(INITIAL);
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 622 "yare.l"
// eat comment in chunks
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 623 "yare.l"
// eat the lone star
	YY_BREAK
case 120:
/* rule 120 can match eol */
YY_RULE_SETUP
#line 624 "yare.l"
yylineno++;
	YY_BREAK

case 121:
YY_RULE_SETUP
#line 627 "yare.l"
{ cout << "Caracter desconocido: '" << yytext << '\'' << endl; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 629 "yare.l"
ECHO;
	YY_BREAK
#line 1906 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(IN_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 322 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 322 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 321);

	return yy_is_jam ? 0 : yy_current_state;
}

    void yyFlexLexer::yyunput( int c, register char* yy_bp)
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream* input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

extern "C" int isatty (int );

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 629 "yare.l"



int yywrap( void ) { return 1; }
