
#line 3 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int FlexScanner::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[251] =
    {   0,
        0,    0,    0,    0,    0,    0,   96,   94,   87,   88,
       86,   86,   94,   86,   86,   86,   86,   86,   86,   86,
       86,   86,    1,    1,   86,   86,   86,   86,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,   86,    2,   94,   95,
       91,   93,   92,   34,    0,   80,    0,    0,   81,    0,
       49,   35,   52,   47,   45,    0,   46,    0,    0,    0,
        0,    0,   89,    0,   48,    0,    1,    0,    0,    0,
       54,    0,   43,   32,   33,   31,   44,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,   22,    0,    0,   71,    0,    0,    0,    0,
       28,   37,    0,    0,    0,    0,    0,    0,    0,    0,
       15,    0,    0,   53,    0,   36,   91,   90,    4,    0,
       85,   39,   42,   41,    0,    0,    0,   82,    1,    5,
        3,    0,   84,   30,   50,   51,   61,    0,   18,   38,
        0,    0,    0,    0,    0,    0,   67,   13,    0,    0,
       69,    0,    0,   12,   14,   58,    0,    0,   27,   17,
       20,   28,   79,    0,    0,    0,    0,    0,   72,    0,
       19,    0,   74,    0,   26,    0,   40,    0,    6,   63,
       64,   65,    0,    8,   66,    0,   68,    0,   23,    0,

        0,    0,    0,   16,    0,    7,   78,   11,   25,   73,
       62,    0,   75,    0,    0,   83,   24,    0,    0,    0,
       70,   57,   55,   10,    0,   21,    0,    0,    0,    0,
        0,    9,    0,   29,   60,    0,    0,    0,    0,    0,
        0,    0,    0,   76,    0,    0,   77,   59,   56,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   14,   21,
       22,   23,   24,   11,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   34,
       50,   51,   52,   53,   10,    1,   25,   26,   27,   28,

       54,   30,   55,   32,   33,   34,   35,   56,   57,   58,
       39,   40,   59,   60,   43,   61,   45,   46,   47,   48,
       49,   34,   14,   62,   14,   14,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    2,    3,    1,    2,    2,    1,    1,    1,    2,
        2,    4,    2,    1,    2,    2,    2,    5,    5,    2,
        1,    2,    1,    1,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        2,    1,    2,    5,    5,    5,    5,    5,    5,    5,
        5,    2
    } ;

static yyconst flex_int16_t yy_base[263] =
    {   0,
        0,    0,    0,    0,   60,   61,  399,  400,  400,  400,
      376,   60,  394,    0,  374,   57,  400,  373,  372,   52,
      377,   58,   65,   69,   49,   71,  370,   54,   71,   36,
       65,   62,   64,   92,  400,   65,   89,   96,  352,   80,
       91,  365,  113,   43,  357,  349,  365,   77,  324,  400,
        0,  400,  368,  400,  119,  400,  381,  380,  400,  375,
      400,  400,  400,  400,  400,  378,  400,  321,  318,  317,
      323,  360,  400,  372,  400,  119,  137,  150,  137,  371,
      400,  350,  350,  400,  400,  400,  349,  327,  330,  340,
      339,  333,  340,   72,  108,  331,  123,  336,  120,  322,

      334,  321,  400,  332,  101,  400,  122,  135,  106,  146,
      139,  400,  318,  151,  142,  149,  150,  149,  168,  154,
      400,  324,  153,  400,  299,  400,    0,  400,  348,  351,
      400,  400,  400,  400,  294,  173,  349,  400,  180,  192,
      400,  348,  400,  400,  400,  400,  400,  307,  400,  400,
      158,  168,  324,  178,  179,  305,  315,  400,  300,  194,
      400,  180,  306,  400,  400,  400,  305,  304,  400,  198,
      400,  400,  400,  191,  315,  309,  297,  311,  285,  184,
      400,  291,  280,  194,  400,  308,  400,  215,  400,  400,
      400,  400,  272,  400,  400,  192,  400,  256,  400,  238,

      191,  195,  196,  400,  196,  400,  400,  400,  400,  400,
      400,  198,  400,  214,  273,  400,  400,  259,  246,  202,
      400,  240,  239,  209,  232,  400,    0,  231,  236,  223,
      227,  400,  219,    0,  400,  241,  220,  187,  168,  224,
      135,  114,   80,  400,  227,  228,  400,  400,  400,  400,
      284,  289,  294,  299,  304,  308,  313,  318,  323,  328,
      333,   84
    } ;

static yyconst flex_int16_t yy_def[263] =
    {   0,
      250,    1,  251,  251,  252,  252,  250,  250,  250,  250,
      250,  253,  254,  255,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  256,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      257,  250,  250,  250,  253,  250,  253,  254,  250,  255,
      250,  250,  250,  250,  250,  258,  250,  250,  250,  250,
      250,  250,  250,  259,  250,  250,  250,  250,  256,  260,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  257,  250,  255,  258,
      250,  250,  250,  250,  250,  250,  259,  250,  250,  250,
      250,  260,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  261,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  261,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  262,  250,  250,  250,
      250,  250,  250,  262,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,    0,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250
    } ;

static yyconst flex_int16_t yy_nxt[463] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,    8,
       17,   18,   19,   17,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   17,   29,   30,   31,   32,   33,   34,
       35,   35,   36,   35,   35,   37,   38,   39,   40,   41,
       35,   42,   43,   44,   35,   35,   45,   46,   35,   17,
        8,   17,   47,   33,   35,   37,   38,   39,   35,   48,
       44,   49,   52,   52,   56,   62,   66,  120,   80,   73,
       81,   53,   53,   67,   74,   86,   87,   94,   63,   75,
       76,  121,   77,   77,   76,   82,   77,   77,  234,   95,
       98,   83,   84,   96,  103,   94,   88,   89,   90,   99,

      153,  116,  104,   97,  247,   68,   69,   70,   91,   71,
       57,  100,   78,   92,   93,   98,  101,  105,   96,   99,
      107,  112,  104,   56,  108,  153,  106,  102,   91,  113,
      125,   93,  114,  169,  109,  115,  139,  139,  246,  112,
      110,  105,  105,  154,  165,  117,  106,  102,  159,  108,
      114,  170,   76,  118,   77,   77,  141,  119,  250,  245,
      156,  165,  160,  154,  166,  157,  105,  140,  140,   57,
      167,  118,  168,  159,  140,  140,  140,  140,  140,  140,
      156,  171,  172,  174,  176,  177,  178,  179,  188,  175,
      180,  183,  168,  181,  185,  191,  189,  139,  139,  172,

      243,  171,  177,  140,  182,  192,  178,  179,  180,  140,
      140,  183,  185,  194,  195,  191,  140,  140,  140,  140,
      140,  140,  199,  200,  182,  192,  204,  211,  205,  214,
      188,  242,  221,  194,  195,  218,  222,  223,  189,  224,
      200,  225,  226,  229,  211,  140,  232,  199,  205,  214,
      221,  204,  218,  237,  222,  223,  224,  238,  225,  244,
      239,  229,  248,  249,  241,  240,  232,  226,  236,  235,
      233,  231,  230,  228,  227,  216,  220,  237,  239,  244,
      219,  238,  248,  249,   50,   50,   50,   50,   50,   51,
       51,   51,   51,   51,   55,   55,   55,   55,   55,   58,

       58,   58,   58,   58,   60,   60,  217,   60,   60,   79,
      216,  213,   79,  127,  127,  212,  210,  127,  130,  130,
      130,  130,  130,  137,  137,  137,  137,  137,  142,  142,
      142,  142,  142,  215,  215,  215,  215,  215,  209,  208,
      207,  206,  203,  202,  201,  198,  197,  196,  193,  190,
      143,  138,  187,  131,  129,  186,  184,  173,  164,  163,
      162,  161,  158,  155,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  138,  136,  135,  134,  133,  132,
      131,  129,   59,  250,  128,  126,  124,  123,  122,  116,
      111,   85,   72,   65,   64,   61,   59,   54,  250,    7,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250
    } ;

static yyconst flex_int16_t yy_chk[463] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    6,   12,   16,   20,   44,   25,   22,
       25,    5,    6,   20,   22,   28,   28,   30,   16,   22,
       23,   44,   23,   23,   24,   26,   24,   24,  262,   31,
       32,   26,   26,   31,   36,   30,   29,   29,   29,   33,

       94,   48,   36,   31,  243,   20,   20,   20,   29,   20,
       12,   33,   23,   29,   29,   32,   34,   37,   31,   33,
       38,   40,   36,   55,   38,   94,   37,   34,   29,   41,
       48,   29,   41,  109,   38,   41,   76,   76,  242,   40,
       38,   43,   37,   95,  105,   43,   37,   34,   99,   38,
       41,  109,   77,   43,   77,   77,   79,   43,   79,  241,
       97,  105,   99,   95,  107,   97,   43,   78,   78,   55,
      107,   43,  108,   99,   78,   78,   78,   78,   78,   78,
       97,  110,  111,  114,  115,  115,  116,  117,  136,  114,
      118,  120,  108,  119,  123,  151,  136,  139,  139,  111,

      239,  110,  115,   78,  119,  152,  116,  117,  118,  140,
      140,  120,  123,  154,  155,  151,  140,  140,  140,  140,
      140,  140,  160,  162,  119,  152,  170,  180,  174,  184,
      188,  238,  201,  154,  155,  196,  202,  203,  188,  205,
      162,  212,  214,  220,  180,  140,  224,  160,  174,  184,
      201,  170,  196,  230,  202,  203,  205,  231,  212,  240,
      233,  220,  245,  246,  237,  236,  224,  214,  229,  228,
      225,  223,  222,  219,  218,  215,  200,  230,  233,  240,
      198,  231,  245,  246,  251,  251,  251,  251,  251,  252,
      252,  252,  252,  252,  253,  253,  253,  253,  253,  254,

      254,  254,  254,  254,  255,  255,  193,  255,  255,  256,
      186,  183,  256,  257,  257,  182,  179,  257,  258,  258,
      258,  258,  258,  259,  259,  259,  259,  259,  260,  260,
      260,  260,  260,  261,  261,  261,  261,  261,  178,  177,
      176,  175,  168,  167,  163,  159,  157,  156,  153,  148,
      142,  137,  135,  130,  129,  125,  122,  113,  104,  102,
      101,  100,   98,   96,   93,   92,   91,   90,   89,   88,
       87,   83,   82,   80,   74,   72,   71,   70,   69,   68,
       66,   60,   58,   57,   53,   49,   47,   46,   45,   42,
       39,   27,   21,   19,   18,   15,   13,   11,    7,  250,

      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[96] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "yare.l"
#line 2 "yare.l"
	#include "yare.tab.h"
	#include "YareScanner.h"
	#include "constantes.h"
	// XXX  #include "astnode.h"
	#include <cstring>
	#include <cctype>
	#include <cstdlib>
	#include <iostream>
	#include <cstdio>
	#include <cstring>

	void append_char(char *s, char c) {
    	unsigned int length = strlen(s);
    	s[length] = c;
    	s[length + 1] = '\0';
	}

	void remove_first_char(char *s) {
    	memmove(s, s + 1, strlen(s));
	}

	void remove_last_char(char *s) {
    	s[strlen(s) - 1] = '\0';
	}

	// Opvar:
	extern char opVar[4];
	// Número de línea:
	extern unsigned int lineno;
	using std::endl;
	using std::cout;
	using std::cerr;


#line 668 "lex.yy.cc"

#define INITIAL 0
#define STRING 1
#define IN_COMMENT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 42 "yare.l"


#line 778 "lex.yy.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = & std::cin;

		if ( ! yyout )
			yyout = & std::cout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 251 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 400 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "yare.l"
{
	lexema->valnum = strtold(yytext, NULL);
	return YL::YareParser::token::NUMERIC;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "yare.l"
{
						// TODO Revisar esto con calma
	if(isupper(*yytext))
		lexema->sIndex = tolower(*yytext) - 'a';
	else
		lexema->sIndex = *yytext - 'a';
	return YL::YareParser::token::VARIABLE;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "yare.l"
{
	strcpy(lexema->identificador, yytext);
	for(unsigned _i_ = 0; _i_ < strlen(lexema->identificador); _i_++)
		if(isalpha(lexema->identificador[_i_]) && isupper(lexema->identificador[_i_]))
			lexema->identificador[_i_] = tolower(lexema->identificador[_i_]);
	return YL::YareParser::token::ID;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "yare.l"
{
	strcpy(lexema->nameFunction, yytext);
	lexema->nameFunction[strlen(lexema->nameFunction)] = '\0';
	return YL::YareParser::token::FUNCNAME;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 72 "yare.l"
{
	lexema->valnum = strtold(yytext, NULL);
	return YL::YareParser::token::NUMERIC;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 77 "yare.l"
{
	// 676 ...? 8729834, expr ...? expr
	return YL::YareParser::token::RANGE_RANDOM;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 82 "yare.l"
{
	return YL::YareParser::token::PROC;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 86 "yare.l"
{
	return YL::YareParser::token::CALL;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 90 "yare.l"
{
	return YL::YareParser::token::PRINTN;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 94 "yare.l"
{
	return YL::YareParser::token::PRINT;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 98 "yare.l"
{
	return YL::YareParser::token::PUTS;	
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 102 "yare.l"
{
	return YL::YareParser::token::INC;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 106 "yare.l"
{
	return YL::YareParser::token::DEC;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 110 "yare.l"
{
	return YL::YareParser::token::LETSET_ASSIGN;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 114 "yare.l"
{
	return YL::YareParser::token::TO;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "yare.l"
{
	return YL::YareParser::token::MOVE;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 122 "yare.l"
{
	// mov x, 1 + 2;
	return YL::YareParser::token::MOV_ASM;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 127 "yare.l"
{
	// dd x, 1+ 2 * 3;
	return YL::YareParser::token::ADD_ASM;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 132 "yare.l"
{
	// add x, 1+ 2 * 3;
	return YL::YareParser::token::SUB_ASM;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 137 "yare.l"
{
	// mul x, 2;
	return YL::YareParser::token::MUL_ASM;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 142 "yare.l"
{
	return YL::YareParser::token::WHILE;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 146 "yare.l"
{
	return YL::YareParser::token::IF;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 150 "yare.l"
{
	return YL::YareParser::token::ELSE;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 154 "yare.l"
{
	return YL::YareParser::token::BREAK;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 158 "yare.l"
{
	return YL::YareParser::token::RAND;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 162 "yare.l"
{
	return YL::YareParser::token::XOROP;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 166 "yare.l"
{
	return YL::YareParser::token::MOD_WORD;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 170 "yare.l"
/* Expressions with WORDS */	{
	return YL::YareParser::token::EXPR_NOT;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 174 "yare.l"
{	
	char *__elemento = strtok(yytext, ".");
	__elemento = strtok(NULL, ".");

	for(unsigned i = 0; i < N_CONST; i++) {
		if(strcmp(__elemento, consts[i].const_str) == 0) {
			lexema->valnum  = consts[i].value;
			return YL::YareParser::token::NUMERIC; 
		}
	}
	cerr << "Error, constante no identificada 'const." << __elemento << "'\n";
	exit(EXIT_FAILURE);
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 188 "yare.l"
{
	return YL::YareParser::token::SWAP_OP;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 192 "yare.l"
{
	// Greater or equal:
	return YL::YareParser::token::GE;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 197 "yare.l"
{
	// Less or equal:
	return YL::YareParser::token::LE;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 202 "yare.l"
{
	// Equal:
	return YL::YareParser::token::EQ;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 207 "yare.l"
{
	// Not equal:
	return YL::YareParser::token::NE;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 212 "yare.l"
{
	return YL::YareParser::token::AND;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 216 "yare.l"
{
	return YL::YareParser::token::OR;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 220 "yare.l"
{
	return YL::YareParser::token::OR;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 224 "yare.l"
{
	return YL::YareParser::token::AND;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 228 "yare.l"
{
	// Equal shell operator ==
	return YL::YareParser::token::EQ;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 233 "yare.l"
{
	// Not equal shell operator !=
	return YL::YareParser::token::NE;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 238 "yare.l"
{
	//  Less shell operator <
	return YL::YareParser::token::_LT_;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 243 "yare.l"
{
	//  Great shell operator >
	return YL::YareParser::token::_GT_;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 248 "yare.l"
{
	return YL::YareParser::token::SHIFTLEFT;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 252 "yare.l"
{					
	return YL::YareParser::token::SHIFTRIGHT; 
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 256 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_MAS;
} 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 260 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_MENOS;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 264 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_MUL;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 268 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_DIV;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 272 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_MOD;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 276 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_SHIFTLEFT;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 280 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_SHIFTRIGHT;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 284 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_AND;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 288 "yare.l"
{
	return YL::YareParser::token::OP_ASIGN_ABR_POW;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 292 "yare.l"
{
	return YL::YareParser::token::PASCAL_ASSIGN;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 296 "yare.l"
{
	// "menor"
	return YL::YareParser::token::EXPR_MENOR;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 301 "yare.l"
{
	// "menorigual"
	return YL::YareParser::token::EXPR_MENORIGUAL;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 306 "yare.l"
{
	// "mayor"
	return YL::YareParser::token::EXPR_MAYOR;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 311 "yare.l"
{
	return YL::YareParser::token::EXPR_MAS;	
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 315 "yare.l"
{
	// "mayorigual"
	return YL::YareParser::token::EXPR_MAYORIGUAL;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 320 "yare.l"
{
	return YL::YareParser::token::EXPR_ELEVADO;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 324 "yare.l"
{
	return YL::YareParser::token::ABS;	
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 328 "yare.l"
{
	return YL::YareParser::token::SQRT;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 332 "yare.l"
{
	return YL::YareParser::token::ACOS;	
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 336 "yare.l"
{
	return YL::YareParser::token::ASIN;	
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 340 "yare.l"
{
	return YL::YareParser::token::ATAN;	
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 344 "yare.l"
{
	return YL::YareParser::token::CEIL;	
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 348 "yare.l"
{
	return YL::YareParser::token::COS;	
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 352 "yare.l"
{
	return YL::YareParser::token::COSH;	
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 356 "yare.l"
{
	return YL::YareParser::token::EXP;		
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 360 "yare.l"
{
	return YL::YareParser::token::FLOOR;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 364 "yare.l"
{
	return YL::YareParser::token::LN;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 368 "yare.l"
{
	return YL::YareParser::token::SIN;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 372 "yare.l"
{
	return YL::YareParser::token::SINH;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 376 "yare.l"
{
	return YL::YareParser::token::TAN;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 380 "yare.l"
{
	   return YL::YareParser::token::TANH;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 384 "yare.l"
{
	return YL::YareParser::token::FACTORIAL;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 388 "yare.l"
{
	return YL::YareParser::token::SUMATORIA;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 392 "yare.l"
{
	return YL::YareParser::token::PUSH;	
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 396 "yare.l"
{
	return YL::YareParser::token::POP;	
}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 400 "yare.l"
{
	// std::cout << "String found: '" << yytext << "'" << endl;
	char *string_final = (char *)malloc(strlen(yytext) + 1);
	string_final[0] = '\0';
    unsigned i;

    bool upper = false;
    bool lower = false;

    for(i = 0; yytext[i] != '\0'; i++) {
        if(yytext[i] == '\\') {
            switch(yytext[i + 1]) {
                case 'n':
                    append_char(string_final, '\n');
                    i++;
                    break;
                case 't':
                    append_char(string_final, '\t');
                    i++;
                    break;
                case 's':
                    append_char(string_final, ' ');
                    i++;
                    break;
                case 'b':
                    append_char(string_final, '\b');
                    i++;
                    break;
                case 'r':
                    append_char(string_final, '\r');
                    i++;
                    break;
                case 'f':
                    append_char(string_final, '\f');
                    i++;
                    break;
                case 'q':
                    append_char(string_final, '"');
                    i++;
                case '\\':
                	append_char(string_final, '\\');
                	i++;
                case 'u':
                	upper = true;
                	i++;
                    break;

                case 'l':
                	lower = true;
                	i++;
                    break;

                default:
                    if(isdigit(yytext[i + 1]) == true) {
                        unsigned n_newline = yytext[i + 1] - '0';
                        unsigned _k = 0;
                        for(_k = 0; _k < n_newline; _k++)
                            append_char(string_final, '\n');
                            i++;
                    }
            }
        } else {
            if(upper && isalpha(yytext[i])) {
            	append_char(string_final, toupper(yytext[i]));
            	upper = false;
            } else if (lower && isalpha(yytext[i])){
            	append_char(string_final, tolower(yytext[i]));
            	lower = false;
            } else {
            	append_char(string_final, yytext[i]);
            }
        }
    }
    
    remove_first_char(string_final);
    remove_last_char(string_final);

    strncpy(lexema->cadena, string_final, strlen(string_final) + 1);

	return YL::YareParser::token::CADENA;
}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 482 "yare.l"
{;}		/* Comentarios tipo shell, perl, python, etc */
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 483 "yare.l"
{;}		/* Comentarios estilo C++ */
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 484 "yare.l"
{;}		/* Comentarios estilo basic */
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 485 "yare.l"
{;}		/* Comentarios estilo batch */
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 486 "yare.l"
{;}		/* Comentarios estilo SQL */
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 488 "yare.l"
{
	return *yytext;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 492 "yare.l"
{;}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 493 "yare.l"
{ ; }
	YY_BREAK

case 89:
YY_RULE_SETUP
#line 496 "yare.l"
BEGIN(IN_COMMENT);
	YY_BREAK


case 90:
YY_RULE_SETUP
#line 499 "yare.l"
BEGIN(INITIAL);
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 500 "yare.l"
// eat comment in chunks
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 501 "yare.l"
// eat the lone star
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 502 "yare.l"
yylineno++;
	YY_BREAK

case 94:
YY_RULE_SETUP
#line 505 "yare.l"
{ cout << "Caracter desconocido: '" << yytext << '\'' << endl; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 507 "yare.l"
ECHO;
	YY_BREAK
#line 1638 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(IN_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 251 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 251 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 250);

	return yy_is_jam ? 0 : yy_current_state;
}

    void yyFlexLexer::yyunput( int c, register char* yy_bp)
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream* input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

extern "C" int isatty (int );

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 507 "yare.l"



