
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 141
#define YY_END_OF_BUFFER 142
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[369] =
    {   0,
        0,    0,    0,    0,  142,  140,  138,  139,   29,   11,
      140,   29,   29,   29,   94,   29,   29,   29,   29,   29,
       29,    3,    3,   29,   29,   29,   29,   29,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,   29,
      140,    2,  140,   22,   21,   20,   22,   45,    0,   24,
        0,   68,    0,   47,   71,    0,   65,   63,    0,   64,
        0,    0,    0,    0,    0,   73,   23,    0,   66,    0,
        3,    4,    0,    0,   75,   74,    0,   31,   76,   32,
       49,   41,   43,   38,   50,    9,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   97,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   98,
        0,    0,  127,    0,    0,    0,   56,   83,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  116,    0,    0,    0,    0,    0,
       67,    0,    0,   72,   48,   19,   15,   17,   12,   18,
       16,   14,   13,    7,    0,   93,    0,   28,   44,   39,
       37,   42,   36,   46,  136,    0,   25,    3,    6,    8,
        0,   27,   40,   69,   70,  104,    0,  112,   82,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  123,    0,

        0,    0,    0,    0,   35,    0,    0,  125,    0,    0,
       79,    0,    0,    0,   89,   33,   51,    0,    0,  117,
       56,  102,  135,   55,    0,    0,    0,    0,    0,    0,
        0,  101,  128,    0,    0,    0,  113,    0,    0,  130,
        0,    0,    0,    0,    0,   62,   95,    0,    0,  136,
      119,    0,  120,    0,  121,   91,    0,   80,  122,    0,
      124,    0,    0,   86,    0,   99,    0,    0,   78,    0,
        0,    0,    0,    0,   85,    0,    0,  114,    0,    0,
       77,  133,  110,  108,  100,  129,    0,  118,    0,    0,
        0,  131,   34,    0,    0,   92,    0,    0,   26,    0,

       30,    0,  109,    0,    0,    0,    0,   53,    0,  126,
        0,    0,    0,   10,   59,   58,   52,    0,  101,   54,
        0,    0,    0,    0,    0,   96,    0,  115,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  103,
      111,    0,  132,   81,    0,    1,    5,   90,   87,   57,
        0,   84,    0,    0,    0,  105,    0,  134,    0,    0,
       88,   61,   60,    0,  137,  106,  107,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   16,   23,
       24,   25,   16,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   36,
       52,   53,   54,   55,   56,    1,   27,   57,   29,   30,

       58,   59,   60,   34,   61,   36,   37,   62,   63,   64,
       65,   66,   67,   68,   69,   70,   47,   48,   49,   50,
       51,   36,   16,   71,   16,   16,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[72] =
    {   0,
        1,    2,    3,    4,    1,    4,    4,    1,    1,    1,
        4,    4,    4,    1,    4,    1,    4,    4,    4,    5,
        5,    2,    1,    4,    1,    4,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    1,    4,    1,    4,    2,    6,    6,    6,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        4
    } ;

static yyconst flex_int16_t yy_base[380] =
    {   0,
        0,    0,   69,   70,  650,  651,  651,  651,  625,  651,
      645,    0,   50,   67,  637,  651,  622,  621,   66,   60,
       68,   75,   79,   89,   62,  620,   56,    0,  133,   66,
       78,   75,  106,  110,  625,  651,  127,   63,  123,   73,
       73,  165,  122,  207,  155,   78,  135,  608,  106,  617,
      614,  156,  128,  651,  651,  651,  216,  651,  636,  651,
      630,  651,  571,  651,  651,  625,  651,  651,  632,  651,
      567,   62,  137,  575,  614,  651,  651,  628,  651,   68,
      195,  651,    0,  186,  195,  199,  627,  651,  200,  604,
      604,  651,  651,  651,  603,    0,  129,  153,  596,  595,

      161,  190,  597,  191,  127,  201,   94,  200,  594,  203,
      221,  204,  201,  246,  593,  235,  234,  242,  206,  651,
      258,  243,  651,  246,  252,  573,  247,  651,  250,  254,
      268,  265,  259,  593,  568,  255,  268,  286,  277,  280,
      298,  282,  290,  153,  651,  298,  294,  270,  304,  296,
      651,  562,  314,  651,  651,  651,  651,  651,  651,  651,
      651,  651,  651,  609,  546,  651,  612,  651,  651,  651,
      651,  651,  651,  651,  596,  610,  651,  326,    0,  651,
      609,  651,  651,  651,  651,  651,  297,  651,  651,  584,
      304,  314,  310,  314,  583,  318,  319,  313,  575,  334,

      332,  560,  336,  327,  651,  335,  337,  651,  338,  344,
      340,  543,  371,  343,  651,  651,  651,  347,  352,  368,
      651,  651,  651,  651,  355,  361,  542,  531,  359,  529,
      511,  651,  502,  361,  360,  372,  651,  508,  367,  500,
      374,  384,  374,  503,  381,  651,  651,  528,  469,  511,
      651,  476,  651,  385,  651,  651,  488,  651,  651,  374,
      651,  383,  496,  651,  493,  651,  468,  390,  651,  382,
      383,  490,  385,  429,  651,  388,  391,  651,  436,  387,
      651,  651,  651,  651,  651,  651,  408,  651,  410,  406,
      422,  651,  651,  409,  423,  651,  430,  367,  651,  288,

      651,  423,  651,  301,  235,  423,  231,  651,  425,  651,
      231,  429,  452,  651,  428,  431,  651,  440,  439,  651,
      441,  441,  444,  440,  448,  651,  193,  651,    0,  454,
      446,  453,  461,  215,  456,  466,  197,  194,  467,  651,
      651,  456,  651,  651,  177,  651,    0,  651,  109,  651,
       77,  651,  468,  480,  481,  651,  479,  651,  482,  475,
      651,  651,  651,   71,  651,  651,  651,  651,  542,  549,
      556,  562,  568,  575,  582,  585,  591,  598,  600
    } ;

static yyconst flex_int16_t yy_def[380] =
    {   0,
      368,    1,  369,  369,  368,  368,  368,  368,  368,  368,
      370,  371,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  372,  368,  368,  368,  373,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  370,  368,
      371,  368,  368,  368,  368,  368,  368,  368,  374,  368,
      368,  368,  368,  368,  368,  368,  368,  375,  368,  368,
      368,  368,  376,  372,  372,  372,  377,  368,  372,  368,
      368,  368,  368,  368,  368,  373,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  371,  368,  368,  374,  368,  368,  368,
      368,  368,  368,  368,  368,  375,  368,  368,  376,  368,
      377,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  378,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  378,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  379,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  379,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,    0,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368
    } ;

static yyconst flex_int16_t yy_nxt[723] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   16,   17,   18,   16,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   36,   36,   38,   39,   40,
       41,   42,   36,   43,   44,   45,   46,   47,   48,   49,
       36,   16,    6,   16,   50,   51,   30,   33,   34,   35,
       37,   38,   39,   40,   41,   42,   36,   52,   44,   45,
       53,   55,   55,   62,   56,   56,   64,   75,   90,   94,
       95,   77,   69,   76,   91,   92,   78,  178,  178,   70,
       65,   79,   80,  122,   81,   81,   80,  367,   81,   81,

       85,   86,  123,  360,  106,  109,  104,   82,  107,  105,
       87,   82,   88,  127,   63,  110,  128,  146,  108,  170,
      122,   57,   57,   71,   83,   72,  123,   73,  197,   74,
      104,  171,  109,  105,   82,  107,  115,  127,   82,  110,
      128,  146,  108,  111,  112,  113,  150,  116,  133,  124,
      117,  154,  134,  125,  197,  114,  118,  195,  120,   89,
       97,   98,   99,  126,  359,  147,  121,  111,  112,  113,
      150,  116,  100,  186,  117,  148,  101,  102,  103,  134,
      125,  143,  133,  241,  195,  120,  134,  126,  144,   97,
      121,  129,  147,  187,  172,  145,  100,  186,  155,  148,

      101,  102,  103,  358,  190,  130,  173,  180,  131,  368,
      241,  132,   80,  153,   81,   81,  180,  187,  368,  145,
      180,  180,  368,  368,  191,  213,  213,   82,  190,  130,
      205,  194,  131,  135,  192,  156,  156,  136,  196,  198,
      355,  137,  201,  354,  199,  204,  206,  138,  352,  139,
      191,  202,  140,  141,   82,  194,  346,  142,  192,  334,
      332,  330,  196,  198,  136,  203,  201,  137,  199,  204,
      206,  138,  157,  139,  158,  210,  140,  211,  202,  159,
      207,  212,  160,  161,  162,  163,  214,  208,  216,  203,
      217,  219,  221,  222,  225,  223,  218,  224,  230,  210,

      216,  211,  226,  215,  244,  212,  207,  233,  227,  228,
      229,  208,  216,  234,  217,  219,  221,  222,  329,  223,
      235,  224,  230,  236,  216,  237,  239,  215,  226,  240,
      244,  233,  227,  228,  229,  242,  238,  243,  245,  246,
      231,  251,  234,  253,  235,  178,  178,  236,  254,  255,
      239,  256,  327,  240,  237,  258,  259,  260,   82,  242,
      238,  243,  205,  246,  245,  251,  266,  253,  262,  299,
      272,  263,  267,  255,  254,  256,  248,  264,  268,  258,
      259,  260,  269,  270,  271,   82,  275,  276,  274,  205,
      213,  213,  277,  266,  262,  263,  267,  272,  278,  279,

      280,  264,  268,  283,  287,  288,  269,  270,  271,  289,
      275,  276,  291,  293,  294,  295,  277,  302,  297,  304,
      308,  305,  309,  279,  280,  278,  310,  283,  287,  288,
      312,  315,  319,  289,  316,  317,  291,  293,  320,  295,
      321,  294,  297,  304,  302,  305,  309,  308,  313,  313,
      310,  322,  323,  324,  312,  315,  319,  325,  316,  317,
      326,  314,  328,  335,  318,  320,  331,  321,  333,  336,
      337,  313,  313,  338,  339,  322,  349,  324,  340,  323,
      341,  342,  343,  325,  344,  345,  328,  326,  314,  335,
      331,  348,  333,  350,  337,  351,  353,  338,  314,  357,

      339,  356,  340,  349,  341,  342,  343,  361,  344,  345,
      362,  363,  366,  364,  365,  348,  311,  350,  296,  307,
      353,  351,  306,  357,  303,  314,  301,  356,  250,  300,
      299,  361,  296,  292,  290,  286,  366,  362,  363,  364,
      285,  365,   54,   54,   54,   54,   54,   54,   54,   59,
       59,   59,   59,   59,   59,   59,   61,   61,  284,   61,
       61,   61,   61,   84,  282,   84,   84,   84,   84,   96,
      281,  273,   96,   96,   96,  167,  167,  167,  167,  167,
      167,  167,  176,  176,  176,  176,  176,  176,  176,  179,
      179,  181,  181,  181,  181,  181,  181,  181,  298,  298,

      298,  298,  298,  298,  298,  347,  347,  265,  261,  257,
      252,  182,  177,  250,  168,  249,  164,  247,  232,  231,
      220,  209,  200,  193,  189,  188,  185,  184,  183,  182,
      177,  175,  174,  169,  168,  166,  165,  164,   60,  152,
      151,  149,  119,   93,   68,   67,   66,   60,   58,  368,
        5,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368
    } ;

static yyconst flex_int16_t yy_chk[723] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,   13,    3,    4,   14,   20,   25,   27,
       27,   21,   19,   20,   25,   25,   21,   80,   80,   19,
       14,   21,   22,   38,   22,   22,   23,  364,   23,   23,

       24,   24,   38,  351,   31,   32,   30,   22,   31,   30,
       24,   23,   24,   40,   13,   32,   41,   46,   31,   72,
       38,    3,    4,   19,   22,   19,   38,   19,  107,   19,
       30,   72,   32,   30,   22,   31,   34,   40,   23,   32,
       41,   46,   31,   33,   33,   33,   49,   34,   43,   39,
       34,   53,   43,   39,  107,   33,   34,  105,   37,   24,
       29,   29,   29,   39,  349,   47,   37,   33,   33,   33,
       49,   34,   29,   97,   34,   47,   29,   29,   29,   43,
       39,   45,   52,  144,  105,   37,   52,   39,   45,   29,
       37,   42,   47,   98,   73,   45,   29,   97,   53,   47,

       29,   29,   29,  345,  101,   42,   73,   84,   42,   84,
      144,   42,   81,   52,   81,   81,   85,   98,   85,   45,
       86,   89,   86,   89,  102,  119,  119,   81,  101,   42,
      113,  104,   42,   44,  102,   57,   57,   44,  106,  108,
      338,   44,  110,  337,  108,  112,  113,   44,  334,   44,
      102,  111,   44,   44,   81,  104,  327,   44,  102,  311,
      307,  305,  106,  108,   44,  111,  110,   44,  108,  112,
      113,   44,   57,   44,   57,  116,   44,  117,  111,   57,
      114,  118,   57,   57,   57,   57,  121,  114,  122,  111,
      124,  125,  127,  129,  131,  130,  124,  130,  133,  116,

      136,  117,  131,  121,  148,  118,  114,  137,  131,  132,
      132,  114,  122,  138,  124,  125,  127,  129,  304,  130,
      139,  130,  133,  140,  136,  141,  142,  121,  131,  143,
      148,  137,  131,  132,  132,  146,  141,  147,  149,  150,
      153,  187,  138,  191,  139,  178,  178,  140,  192,  193,
      142,  194,  300,  143,  141,  196,  197,  198,  178,  146,
      141,  147,  201,  150,  149,  187,  203,  191,  200,  298,
      211,  200,  204,  193,  192,  194,  153,  200,  206,  196,
      197,  198,  207,  209,  210,  178,  214,  218,  213,  201,
      213,  213,  219,  203,  200,  200,  204,  211,  220,  225,

      226,  200,  206,  229,  234,  235,  207,  209,  210,  236,
      214,  218,  239,  241,  242,  243,  219,  254,  245,  260,
      268,  262,  270,  225,  226,  220,  271,  229,  234,  235,
      273,  276,  280,  236,  277,  277,  239,  241,  287,  243,
      289,  242,  245,  260,  254,  262,  270,  268,  274,  274,
      271,  290,  291,  294,  273,  276,  280,  295,  277,  277,
      297,  274,  302,  312,  279,  287,  306,  289,  309,  313,
      315,  313,  313,  316,  318,  290,  331,  294,  319,  291,
      321,  322,  323,  295,  324,  325,  302,  297,  274,  312,
      306,  330,  309,  332,  315,  333,  335,  316,  336,  342,

      318,  339,  319,  331,  321,  322,  323,  353,  324,  325,
      354,  355,  360,  357,  359,  330,  272,  332,  267,  265,
      335,  333,  263,  342,  257,  336,  252,  339,  250,  249,
      248,  353,  244,  240,  238,  233,  360,  354,  355,  357,
      231,  359,  369,  369,  369,  369,  369,  369,  369,  370,
      370,  370,  370,  370,  370,  370,  371,  371,  230,  371,
      371,  371,  371,  372,  228,  372,  372,  372,  372,  373,
      227,  212,  373,  373,  373,  374,  374,  374,  374,  374,
      374,  374,  375,  375,  375,  375,  375,  375,  375,  376,
      376,  377,  377,  377,  377,  377,  377,  377,  378,  378,

      378,  378,  378,  378,  378,  379,  379,  202,  199,  195,
      190,  181,  176,  175,  167,  165,  164,  152,  135,  134,
      126,  115,  109,  103,  100,   99,   95,   91,   90,   87,
       78,   75,   74,   71,   69,   66,   63,   61,   59,   51,
       50,   48,   35,   26,   18,   17,   15,   11,    9,    5,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,

      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368,  368,  368,  368,  368,  368,  368,  368,  368,
      368,  368
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./lexico.l"
/* Leo Gutiérrez Ramírez, leorocko13@hotmail.com */
#line 3 "./lexico.l"
	#include <stdlib.h>
	#include "estructuras.h"
	#include "constantes.h"
	#include "y.tab.h"
	extern char opVar[4];
	extern unsigned int lineno;
	char buf[100];
	char *str_scapes;			/* Puntero para ir acumulando caracteres de escape */

#line 753 "lex.yy.c"

#define INITIAL 0
#define STRING 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 14 "./lexico.l"


#line 944 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 369 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 651 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "./lexico.l"
yylineno;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 18 "./lexico.l"
{
						/* TODO Revisar esto con calma */
						if(isupper(*yytext))
							yylval.sIndex = tolower(*yytext) - 'a';
						else
							yylval.sIndex = *yytext - 'a';
						return VARIABLE;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "./lexico.l"
{
						yylval.iValue = strtod(yytext, NULL);
						return INTEGER;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "./lexico.l"
{
		/* Cortar la 'g' */
		yytext[strlen(yytext) - 1] = '\0';		
		strcpy(yylval.cadena_gigante, yytext);
		return GIGANTE;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "./lexico.l"
{	
									char *__elemento = strtok(yytext, ".");
									__elemento = strtok(NULL, ".");

									unsigned i;
									for(i = 0; i < N_CONST; i++) 
										if(strcmp(__elemento, consts[i].const_str) == 0) {
											yylval.iValue = consts[i].value;
											return INTEGER;
										}
									fprintf(stderr, "Error, constante no identificada 'const.%s'\n", __elemento);
									exit(EXIT_FAILURE);
								}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "./lexico.l"
{
							yylval.iValue = atof(yytext);
						return INTEGER;
					}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "./lexico.l"
{
						strcpy(yylval.nameFunction, yytext);
						yylval.nameFunction[strlen(yylval.nameFunction)] = '\0';
						return FUNCNAME;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 63 "./lexico.l"
{
							unsigned _i_;
							strcpy(yylval.identificador, yytext);
							for(_i_ = 0; _i_ < strlen(yylval.identificador); _i_++)
								if(isalpha(yylval.identificador[_i_]) && isupper(yylval.identificador[_i_]))
									yylval.identificador[_i_] = tolower(yylval.identificador[_i_]);
							return ID;
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "./lexico.l"
{
							
							unsigned _i_;
							strcpy(yylval.idArray, yytext);
							for(_i_ = 0; _i_ < strlen(yylval.idArray); _i_++)
								if(isalpha(yylval.idArray[_i_]) && isupper(yylval.idArray[_i_]))
									yylval.idArray[_i_] = tolower(yylval.idArray[_i_]);
							return ID_ARRAY;

}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "./lexico.l"
{
	/* Detección de gigantes: */
	/* Cortando los caracteres sobrantes: */
	*yytext++;
	*yytext++;
	yytext[strlen(yytext) - 1] = '\0';
	yytext[strlen(yytext) - 1] = '\0';
	unsigned _i_;
	strcpy(yylval.idgigante, yytext);
	for(_i_ = 0; _i_ < strlen(yylval.idgigante); _i_++)
		if(isalpha(yylval.idgigante[_i_]) && isupper(yylval.idgigante[_i_]))
			yylval.idgigante[_i_] = tolower(yylval.idgigante[_i_]);
	/*printf("Gigante detectado '%s'-'%d'\n", yylval.idgigante, strlen(yylval.idgigante));*/
	return ID_GIGANTE;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 98 "./lexico.l"
{ BEGIN	STRING; str_scapes = buf; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 99 "./lexico.l"
{ *str_scapes++ = '\n'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 100 "./lexico.l"
{ *str_scapes++ = '\t'; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 101 "./lexico.l"
{ *str_scapes++ = ' ';  }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 102 "./lexico.l"
{ *str_scapes++ = '\b'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 103 "./lexico.l"
{ *str_scapes++ = '\r'; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 104 "./lexico.l"
{ *str_scapes++ = '\f'; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "./lexico.l"
{ *str_scapes++ = '"'; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "./lexico.l"
{ 
					int _ii;
					/* Caracteres de escape numéricos para saltos de línea */
					for(_ii = 0; _ii < (*(yytext + 1) - '0'); _ii++) 
						*str_scapes++ = '\n';	
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 112 "./lexico.l"
{
						*str_scapes = 0;
						BEGIN 0; 
						/* REGRESAR EL STRING Y ASIGNARLO AQUÍ */
						strcpy(yylval.cadena, buf);
						return CADENA;
					}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 119 "./lexico.l"
{ printf("Error, Invalid string at line: %d\n", lineno + 1); exit(EXIT_FAILURE);	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 120 "./lexico.l"
{ *str_scapes++ = *yytext; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 122 "./lexico.l"
{comment();}	/* Comentarios */
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 123 "./lexico.l"
{;}		/* Comentarios tipo shell, perl, python, etc */
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 124 "./lexico.l"
{;}		/* Comentarios estilo C++ */
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 125 "./lexico.l"
{;}		/* Comentarios estilo basic */
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 126 "./lexico.l"
{;}		/* Comentarios estilo batch */
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 127 "./lexico.l"
{;}		/* Comentarios estilo SQL */
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 129 "./lexico.l"
{
									return *yytext;
					}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "./lexico.l"
return ARRAY;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "./lexico.l"
return ASIGNACION_PASCAL;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "./lexico.l"
return ASIGNACION_PASCAL;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "./lexico.l"
return LETSET;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "./lexico.l"
return IFTHEN;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 138 "./lexico.l"
return IFEND;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 140 "./lexico.l"
return _LT_;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 141 "./lexico.l"
return _GT_;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 142 "./lexico.l"
return GE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 143 "./lexico.l"
return GE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 144 "./lexico.l"
return SWAP;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 145 "./lexico.l"
return LE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 146 "./lexico.l"
return LE;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 147 "./lexico.l"
return EQ;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 148 "./lexico.l"
return EQ;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 149 "./lexico.l"
return NE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 150 "./lexico.l"
return NE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 151 "./lexico.l"
return AND;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 152 "./lexico.l"
return OR;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 153 "./lexico.l"
return SHIFTLEFT;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 154 "./lexico.l"
return SHIFTRIGHT; 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 156 "./lexico.l"
return EXPR_MAS;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 157 "./lexico.l"
return EXPR_MENOS;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 158 "./lexico.l"
return EXPR_DIV;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 159 "./lexico.l"
return EXPR_DIV;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 160 "./lexico.l"
return EXPR_MUL;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 161 "./lexico.l"
return EXPR_NOT;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 162 "./lexico.l"
return EXPR_ELEVADO;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 163 "./lexico.l"
return EXPR_MENOR;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 164 "./lexico.l"
return EXPR_MAYOR;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 165 "./lexico.l"
return EXPR_MENORQUE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 166 "./lexico.l"
return EXPR_MAYORQUE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 168 "./lexico.l"
return XOROP;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 170 "./lexico.l"
return ASIGN_ADD;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 171 "./lexico.l"
return ASIGN_SUB;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 172 "./lexico.l"
return ASIGN_MUL;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 173 "./lexico.l"
return ASIGN_DIV;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 174 "./lexico.l"
return ASIGN_POW;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 175 "./lexico.l"
return ASIGN_MOD;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 176 "./lexico.l"
return ASIGN_SHIFTLEFT;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 177 "./lexico.l"
return ASIGN_SHIFTRIGHT;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 178 "./lexico.l"
return ASIGN_AND;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 179 "./lexico.l"
return ASIGN_OR;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 180 "./lexico.l"
return CONCATENATE_DIGITS;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 181 "./lexico.l"
return FACE_HAPPY;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 182 "./lexico.l"
return FACE_SAD;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 183 "./lexico.l"
return FACE_NO;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 185 "./lexico.l"
return PROC;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 186 "./lexico.l"
return EXIT;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 187 "./lexico.l"
return FOR;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 188 "./lexico.l"
return CALL;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 189 "./lexico.l"
return UNLESS;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 190 "./lexico.l"
return AND;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 191 "./lexico.l"
return OR;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 192 "./lexico.l"
return FOREACH;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 193 "./lexico.l"
return INCREMENTAR;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 194 "./lexico.l"
return DECREMENTAR;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 195 "./lexico.l"
return DECLARE;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 196 "./lexico.l"
return FUNCTION;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 197 "./lexico.l"
return INT_TYPE;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 198 "./lexico.l"
return DECIMAL_TYPE;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 199 "./lexico.l"
return BOOL_TYPE;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 200 "./lexico.l"
return VOID;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 201 "./lexico.l"
return ANDBITS;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 202 "./lexico.l"
return ORBITS;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 203 "./lexico.l"
return OPVAR;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 204 "./lexico.l"
return WHILE;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 205 "./lexico.l"
return DO;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 206 "./lexico.l"
return IF;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 207 "./lexico.l"
return ELSE;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 208 "./lexico.l"
return READ;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 209 "./lexico.l"
return PRINT;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 210 "./lexico.l"
return PAR;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 211 "./lexico.l"
return PRINTN;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 212 "./lexico.l"
return ABS;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 213 "./lexico.l"
return PRASCII;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 214 "./lexico.l"
return FACTORIAL;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 215 "./lexico.l"
return SUMATORIA;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 216 "./lexico.l"
return RAND;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 217 "./lexico.l"
return BREAK;
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 218 "./lexico.l"
return PUTS;
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 219 "./lexico.l"
return STRLEN;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 220 "./lexico.l"
return ADDASM;
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 221 "./lexico.l"
return SUBASM;
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 222 "./lexico.l"
return MOVE;
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 223 "./lexico.l"
return MOVE;
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 224 "./lexico.l"
return TO;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 225 "./lexico.l"
return MOVASM;
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 227 "./lexico.l"
return SQRT;
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 228 "./lexico.l"
return ACOS;
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 229 "./lexico.l"
return ASIN;
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 230 "./lexico.l"
return ATAN;
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 231 "./lexico.l"
return CEIL;
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 232 "./lexico.l"
return COS;
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 233 "./lexico.l"
return COSH;
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 234 "./lexico.l"
return EXP;
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 235 "./lexico.l"
return FLOOR;
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 236 "./lexico.l"
return LN;
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 237 "./lexico.l"
return SIN;
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 238 "./lexico.l"
return SINH;
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 239 "./lexico.l"
return TAN;
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 240 "./lexico.l"
return TANH;
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 241 "./lexico.l"
return SYSTEM;
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 243 "./lexico.l"
return PUSH;
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 244 "./lexico.l"
return VER_PILA;
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 245 "./lexico.l"
return POP;
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 247 "./lexico.l"
return ELIPSIS;
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 249 "./lexico.l"
return DECLARE_G;	/* declare_g(...); */
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 251 "./lexico.l"
;
	YY_BREAK
case 139:
/* rule 139 can match eol */
YY_RULE_SETUP
#line 252 "./lexico.l"
{ lineno++; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 253 "./lexico.l"
{
				char __linea[40];
				sprintf(__linea, "Carácter desconocido en la línea %d\n", lineno + 1);
				fputs(__linea, stdout);

				/* FIXME Decidir si se va a continuar o al error parar todo */
				
				/*yyerror(__linea);*/
	}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 263 "./lexico.l"
ECHO;
	YY_BREAK
#line 1824 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 369 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 369 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 368);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 263 "./lexico.l"



comment()
{
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0);
/*		putchar(c);*/

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	/*if (c != 0)
		putchar(c1);*/
}

int yywrap(void) {
	return 1;
}

